package clientChat;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.Base64;

@Controller
@Slf4j
public class GreetingController {
    //  private Logger log;

    static Long id;
    @Autowired
    private SimpMessagingTemplate template;

    //при подписке на topic/greetings вызывает метод message
    @MessageMapping("/hello")
    public void gotMessage(MessageApp message) throws Exception {
        System.out.println("Received " + message.getContent());
        System.out.println("Received Id" + message.getId());
        System.out.println("Received Email " + message.getEmailSender());
        EventApp evap = eventRepository.findById(message.getId()).get();
        Message dialogue = new Message();
        dialogue.setFrom(message.getEmailSender());
        dialogue.setMessage(message.getContent());
        ArrayList<Message> list = evap.getMessage();
        if (list == null)
            list = new ArrayList<>();
        list.add(dialogue);
        evap.setMessage(list);
        eventRepository.save(evap);
        template.convertAndSend("/topic/greeting" + message.getId(), message);
    }


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private EventsRepository eventRepository;


    @RequestMapping(value = "/post", method = RequestMethod.POST, headers = "Accept=application/json")
    @ResponseBody
    public String post(@RequestBody Event image) {
        System.out.println("/POST request with " + image.toString());
        // save Image to C:\\server folder
        String path = "C:\\server\\" + image.getID() + ".png";
        String s = Base64.getEncoder().encodeToString(image.getImage());
        UtilBase64Image.decoder(s, path);
        EventApp event = new EventApp();

        event.setDecription(image.getDescribe());
        event.setName(image.getTitle());
        event.setPlace(image.getPlace());
        event.setImage(image.getImage());
        event.setDate(image.getDate());
        event.setKind(image.getKind());
        event.setTime(image.getTime());
        ArrayList<Long> arrU = null;
        UserApp cur = null;
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(image.getAuthor())) {
                ArrayList<String> arr = event.getPeople();
                arr.add(Long.toString(u.getId()));
                event.setPeople(arr);
                arrU = u.getEventsSub();
                cur = u;
                break;
            }
        }
        event.setAuthor(image.getAuthor());
        eventRepository.save(event);
        arrU.add(event.getId());
        cur.setEventsSub(arrU);
        userRepository.save(cur);
        template.convertAndSend("/topic/greeting/eventUpdate",
                new MessageApp("MessageApp for all"));
        // This returns a JSON or XML with the users
        return Long.toString(event.getId());
    }

    //add user
    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name
            , @RequestParam String email, @RequestParam String password, @RequestParam String age, @RequestParam String city) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        UserApp n = new UserApp();
        n.setmName(name);
        n.setEmail(email);
        n.setPassword(password);
        n.setAge(age);
        n.setCity(city);
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email))
                return "0";
        }
        userRepository.save(n);
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email))
                return "" + u.getId();
        }
        return "0";
    }

    @RequestMapping(value = "/postUser", method = RequestMethod.POST, headers = "Accept=application/json")
    @ResponseBody
    public String postUser(@RequestBody User image) {
        System.out.println("/POST request with " + image.toString());
        // save Image to C:\\server folder
        String path = "C:\\server\\" + image.getEmail() + ".png";
        String s = Base64.getEncoder().encodeToString(image.getImage());
        UtilBase64Image.decoder(s, path);
        UserApp user = new UserApp();
        user.setAge(image.getAge());
        user.setCity(image.getCity());
        user.setEmail(image.getEmail());
        user.setmName(image.getName());
        user.setPassword(image.getPassword());
        user.setImage(image.getImage());
        userRepository.save(user);
        // This returns a JSON or XML with the users
        return Long.toString(user.getId());
    }


    @RequestMapping(value = "/postUserUpdate", method = RequestMethod.POST, headers = "Accept=application/json")
    @ResponseBody
    public void postUserUpdate(@RequestBody User image) {
        for (UserApp a : userRepository.findAll()) {
            if (a.getEmail().equals(image.getEmail())) {
                a.setImage(image.getImage());
                a.setmName(image.getName());
                a.setCity(image.getCity());
                a.setAge(image.getAge());
                userRepository.save(a);
                System.out.println("/POST request with " + image.toString());
                // save Image to C:\\server folder
                String path = "C:\\server\\" + image.getEmail() + ".png";
                String s = Base64.getEncoder().encodeToString(image.getImage());
                UtilBase64Image.decoder(s, path);
                return;
            }
        }


    }


    @GetMapping(path = "/updatePerson")
    public @ResponseBody
    void updatePerson(@RequestParam String email, @RequestParam String name, @RequestParam String age, @RequestParam String city) {
        // This returns a JSON or XML with the users
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email)) {
                u.setCity(city);
                u.setAge(age);
                u.setmName(name);
                userRepository.save(u);
            }
        }

    }


    @GetMapping(path = "/getMessages")
    public @ResponseBody
    MessageArray getMessages(@RequestParam String Id) {
        // This returns a JSON or XML with the users
        Long id = Long.valueOf(Id);
        EventApp event = eventRepository.findById(id).get();
        MessageArray result = new MessageArray();
        result.setMessages(event.getMessage());
        return result;
    }


    @GetMapping(path = "/loginUser")
    public @ResponseBody
    User loginUser(@RequestParam String email, @RequestParam String password) {
        // This returns a JSON or XML with the users
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email) && u.getPassword().equals(password)) {
                User result = new User();
                result.setName(u.getmName());
                result.setAge(u.getAge());
                result.setCity(u.getCity());
                result.setPassword(u.getPassword());
                result.setEmail(u.getEmail());
                result.setId(Long.toString(u.getId()));
                result.setImage(u.getImage());
                return result;
            }
        }
        return null;
    }


    @GetMapping(path = "/AllEvents")
    public @ResponseBody
    ListEvents eventAllReturn() {
        // This returns a JSON or XML with the users

        ArrayList<Event> result = new ArrayList<>();
        for (EventApp u : eventRepository.findAll()) {
            Event event = new Event(Long.toString(u.getId()), u.getName(), u.getDecription(), u.getAuthor());
            event.setImage(u.getImage());
            event.setDate(u.getDate());
            event.setKind(u.getKind());
            event.setTime(u.getTime());
            event.setPlace("");
            result.add(event);
        }
        ListEvents eal = new ListEvents();
        eal.setListEvent(result);
        return eal;
    }


    @GetMapping(path = "/AllEventsOfUser")
    public @ResponseBody
    ListEvents allEventsOfUser(@RequestParam String email) {
        // This returns a JSON or XML with the users

        ArrayList<Event> result = new ArrayList<>();
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email)) {
                ArrayList<Long> arr = u.getEventsSub();
                for (int i = 0; i < arr.size(); i++) {
                    System.out.println(arr.get(i));
                    EventApp ea = eventRepository.findById(arr.get(i)).get();
                    Event curr = new Event(Long.toString(ea.getId()), ea.getName(), ea.getDecription(), ea.getName());
                    result.add(curr);
                    //  System.out.println(result.size());
                }
                ListEvents eal = new ListEvents();
                eal.setListEvent(result);
                return eal;
            }
        }
        return null;
    }

    //Добавить человеку событие в subscribers
    @GetMapping(path = "/addEventToUser")
    public @ResponseBody
    void addEventToUser(@RequestParam String email, @RequestParam String id) {

        Long Id = Long.valueOf(id);
        for (UserApp u : userRepository.findAll()) {
            if (u.getEmail().equals(email)) {
                ArrayList<Long> arr = u.getEventsSub();
                arr.add(Id);
                u.setEventsSub(arr);
                userRepository.save(u);
                //    System.out.println(arr.size());
            }
        }
    }


    //Добавить событию человека в subscribers
    @GetMapping(path = "/addUserToEvent")
    public @ResponseBody
    void addUserToEvent(@RequestParam String email, @RequestParam String id) {

        Long Id = Long.valueOf(id);
        EventApp u = eventRepository.findById(Id).get();

        ArrayList<String> arr = u.getPeople();
        for (UserApp user : userRepository.findAll())
            if (user.getEmail().equals(email)) {
                arr.add(Long.toString(user.getId()));
                u.setPeople(arr);
                eventRepository.save(u);
                return;
            }
    }


    @GetMapping(path = "/findEventById")
    public @ResponseBody
    Event findEventById(@RequestParam String id) {

        Long Id = Long.valueOf(id);
        Event result;
        EventApp evapp = eventRepository.findById(Id).get();
        result = new Event(id, evapp.getName(), evapp.getDecription(), evapp.getAuthor());
        result.setImage(evapp.getImage());

        result.setPlace(evapp.getPlace());
        return result;
    }


    @GetMapping(path = "/deleteById")
    public @ResponseBody
    void deleteById(@RequestParam String id) {
        System.out.println("start");
        Long Id = Long.valueOf(id);
        EventApp event = eventRepository.findById(Id).get();
        ArrayList<String> arr = event.getPeople();
        ArrayList<Long> idUsers = new ArrayList<>();
        for (int i = 0; i < arr.size(); i++) {
            idUsers.add(Long.valueOf(arr.get(i)));
        }
        for (int i = 0; i < idUsers.size(); i++) {
            UserApp u = userRepository.findById(idUsers.get(i)).get();
            ArrayList<Long> arrEv = u.getEventsSub();
            ArrayList<Long> newList = new ArrayList<>();
            for (int j = 0; j < arrEv.size(); j++) {
                System.out.println(arrEv.get(j));
                if (!arrEv.get(j).equals(Id)) {
                    newList.add(arrEv.get(j));
                }

            }
            u.setEventsSub(newList);
            userRepository.save(u);
        }
        eventRepository.deleteById(Id);
    }


    // события пользовтеля
    // TODO
    // хранение картинки
    // getInformationAboutEvents(String email) return EventApp;
    // Все сообщения по Id события
    // AddMessage

    //получение пользователя по почте
}